config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

    root 'static_pages#main_page'
  resources "tweets"

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

	validates :content, length: { minimum: 0, maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page
		tweet = Tweet.all
		@tweet = Tweet.all
	end

	def about_us
	end

	def contact_us
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	def new
		@tweet = Tweet.new
		@tweets = Tweet.all
	end


	def create
		@tweet_to_create = Tweet.new(tweet_params)
		if @tweet_to_create.save
			flash.now["success"] = "Tweet Success"
		else 
			flash.now["danger"] = "404: Danger"
		end 

		

		@tweet = Tweet.new

		@tweets = Tweet.all


		render 'new'

	end

	def edit
	end

	def show
	end

	def index
	end

	def tweet_params
		params.require("tweet").permit("content")
    end 
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
	</head>
<body>
	

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--Embedding a link via ruby instead of html -->
      <%= link_to "Adam", root_path, class: "navbar-brand" %>
      
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "New Tweet Page", new_tweet_path %>
        </li>
        <li>
          <% if user_signed_in? %>
          <% link_to "Log Out", destroy_user_session_path, method: "delete" %>

          <% else %>
          <% link_to "Sign up", new_user_registration_path %>
          <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Reach Me <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="http://www.adam-design.com">SI-Boston</a></li>
            <li><a href="https://plus.google.com/u/0/+AdamBennani/posts">Google+</a></li>
            <li><a href="https://twitter.com/StretchBreaker">Twitter</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Portfolio <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="http://www.adam-design.com">SI-Boston</a></li>
            <li><a href="http://stretchbreaker.herokuapp.com">Personal Server</a></li>
            <li><a href="http://getbootstrap.com/css/#helper-classes-backgrounds">Bootstrap Links</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class= "container">
    <%flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
      <% end %>

      <%= yield %></div>
</body>
</html>

app/views/static_pages/main_page.html.erb
This is the main page

app/views/tweets/new.html.erb
here are where we make new tweets:

<%= simple_form_for @tweet, url: tweets_path, method: 'post' do |f| %>
	 <%= f.input "content" %>
	 <%= f.button "submit", "Create Tweet" %>
<% end %>

Here are all the tweets ever made: <br /><br />

<% @tweets.each do |tweet| %>
	<%=tweet.content %><br />
<% end %>